"""Deterministic primitives shared across the system.

Trimmed copy of assignment-6's ``datasys/util.py``: canonical JSON, content
hashing, and a counter-based (stateless, splittable) PRNG so any random draw is
a pure function of (seed, coordinate) and can be regenerated byte-identically.
"""

from __future__ import annotations

import hashlib
import json
import os
import struct
from typing import Any

# ---------------------------------------------------------------------------
# Canonical serialization + hashing
# ---------------------------------------------------------------------------


def canonical_json(obj: Any) -> str:
    """Deterministic JSON: sorted keys, no insignificant whitespace, UTF-8 safe."""
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_text(text: str) -> str:
    return sha256_bytes(text.encode("utf-8"))


def sha256_json(obj: Any) -> str:
    return sha256_text(canonical_json(obj))


def sha256_array(arr) -> str:
    """Content hash of a numpy array: dtype + shape + raw bytes."""
    import numpy as np

    a = np.ascontiguousarray(arr)
    h = hashlib.sha256()
    h.update(str(a.dtype).encode())
    h.update(str(a.shape).encode())
    h.update(a.tobytes())
    return h.hexdigest()


def short(h: str, n: int = 12) -> str:
    return h[:n]


# ---------------------------------------------------------------------------
# Counter-based PRNG (stateless / splittable)
# ---------------------------------------------------------------------------


def _hash_to_u64(*parts: Any) -> int:
    key = "\x1f".join(str(p) for p in parts)
    digest = hashlib.sha256(key.encode("utf-8")).digest()
    return struct.unpack_from("<Q", digest, 0)[0]


def rand_u64(seed: int, *coord: Any) -> int:
    return _hash_to_u64(seed, *coord)


def rand_float(seed: int, *coord: Any) -> float:
    """Uniform float in [0, 1) that depends only on (seed, coord)."""
    return (rand_u64(seed, *coord) >> 11) / float(1 << 53)


def rand_int(seed: int, lo: int, hi: int, *coord: Any) -> int:
    """Uniform int in [lo, hi) depending only on (seed, coord)."""
    if hi <= lo:
        return lo
    return lo + (rand_u64(seed, *coord) % (hi - lo))


def deterministic_shuffle(items: list, seed: int, *coord: Any) -> list:
    """New list shuffled purely as a function of (seed, coord) via Fisher-Yates."""
    out = list(items)
    n = len(out)
    for i in range(n - 1, 0, -1):
        j = rand_u64(seed, *coord, "shuffle", i) % (i + 1)
        out[i], out[j] = out[j], out[i]
    return out


# ---------------------------------------------------------------------------
# Small filesystem helpers
# ---------------------------------------------------------------------------


def ensure_dir(path: str) -> str:
    os.makedirs(path, exist_ok=True)
    return path


def write_json(path: str, obj: Any) -> str:
    """Write pretty JSON and return the content hash of the canonical form."""
    parent = os.path.dirname(path)
    if parent:
        ensure_dir(parent)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, sort_keys=True, ensure_ascii=False)
        f.write("\n")
    return sha256_json(obj)


def read_json(path: str) -> Any:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)
