// Publish the assignment-7 interactive report as a static GitHub Pages page.
//
// The report is a fully self-contained HTML artifact (figures base64-inlined,
// vanilla-JS demo, no external requests) generated by the assignment's own
// pipeline into submission_artifacts/. Copying it at build time keeps a single
// source of truth: the page always matches the committed artifact bundle, and
// nothing is duplicated in the repo.
import { copyFileSync, mkdirSync } from 'node:fs'

mkdirSync('dist/assignment-7', { recursive: true })
copyFileSync(
  'assignment-7/submission_artifacts/report.html',
  'dist/assignment-7/index.html',
)
console.log('assignment-7 report published -> dist/assignment-7/index.html')
